# Generated by Django 5.1.4 on 2026-06-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_kardexdocente_motivo_documento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['grupo__grado', 'grupo__letra', 'numero_lista', 'alumno__apellidos', 'alumno__nombres']},
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='numero_lista',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
