# Generated by Django 5.1.4 on 2026-06-19 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0007_alter_inscripcion_options_inscripcion_numero_lista'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alergias',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curp',
            field=models.CharField(blank=True, max_length=18, verbose_name='CURP'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='alumno',
            name='genero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='alumno',
            name='institucion_medica',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='alumno',
            name='medicamentos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='numero_seguridad_social',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='alumno',
            name='observaciones_medicas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='padecimientos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='parentesco_emergencia',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='alumno',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='tutor',
            name='direccion',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='tutor',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='parentesco',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tutor',
            name='telefono_alterno',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACTA', 'Acta de nacimiento'), ('CURP', 'CURP'), ('COMPROBANTE_DOMICILIO', 'Comprobante de domicilio'), ('CERTIFICADO_MEDICO', 'Certificado medico'), ('NSS', 'Numero de seguridad social'), ('BOLETA', 'Boleta o calificaciones'), ('IDENTIFICACION_TUTOR', 'Identificacion del tutor'), ('AUTORIZACION', 'Autorizacion'), ('OTRO', 'Otro')], max_length=32)),
                ('nombre', models.CharField(max_length=120)),
                ('archivo', models.FileField(upload_to='alumnos/documentos/')),
                ('notas', models.CharField(blank=True, max_length=220)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='escuela.alumno')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de alumno',
                'verbose_name_plural': 'Documentos de alumnos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='KardexAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ALTA', 'Alta'), ('EDICION', 'Edicion'), ('CAMBIO_GRUPO', 'Cambio de grupo'), ('DOCUMENTO', 'Documento'), ('BAJA', 'Baja u ocultamiento'), ('RESTAURACION', 'Restauracion'), ('SALUD', 'Salud'), ('CONTACTO', 'Contacto'), ('OTRO', 'Otro')], max_length=24)),
                ('referencia', models.CharField(blank=True, max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='escuela.alumno')),
                ('inscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex', to='escuela.inscripcion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kardex alumno',
                'verbose_name_plural': 'Kardex alumnos',
                'ordering': ['-fecha'],
            },
        ),
    ]
